import pathlib
import os
import subprocess
import sys

PATH = pathlib.Path(__file__).parent.resolve()
BASHRC_PATH = os.path.expanduser("~/.bashrc")
VENV_PYTHON_REL_PATH = "venv/bin/python"
MAIN_SCRIPT_REL_PATH = "linux-term-help.py"

ALIAS_PREFIX = "alias helper="
API_KEY_PREFIX = "export GEMINI_API_KEY="

def setup_alias():
    
    python_path = PATH / VENV_PYTHON_REL_PATH
    script_path = PATH / MAIN_SCRIPT_REL_PATH
    
    alias_line = f"alias helper='{python_path} {script_path}'"

    new_block = f"""
# --- Linux Terminal Helper Alias (Auto-Generated) ---
{alias_line}
    """
    
    try:
        with open(BASHRC_PATH, 'a') as f:
            f.write(new_block)
        print(f"[SUCCESS] Alias 'helper' installed in {BASHRC_PATH}.")
    except Exception as e:
        print(f"[FATAL ERROR] Failed to write alias to {BASHRC_PATH}. Check file permissions: {e}", file=sys.stderr)




def fix_alias_path():

    python_path = PATH / VENV_PYTHON_REL_PATH
    script_path = PATH / MAIN_SCRIPT_REL_PATH
    
    new_alias_line = f"alias helper='{python_path} {script_path}'\n"
    
    found_and_fixed = False
    
    try:
        # 1. Read all lines
        with open(BASHRC_PATH, 'r') as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            stripped_line = line.strip()
            
            # Check for the old alias line (must start with prefix and not be a comment)
            if stripped_line.startswith(ALIAS_PREFIX) and not stripped_line.startswith('#'):
                # Replace the old line with the new, correct alias
                new_lines.append(new_alias_line)
                print(f"[REPLACED] Alias line updated from '{stripped_line}'")
                print(f"           to '{new_alias_line.strip()}'")
                found_and_fixed = True
            else:
                new_lines.append(line)

        # 3. Write the modified content back to the file
        if found_and_fixed:
            with open(BASHRC_PATH, 'w') as f:
                f.writelines(new_lines)
            print(f"[SUCCESS] Alias path updated in {BASHRC_PATH}.")
        else:
            print("[WARNING] Could not find the old alias line to replace. No file changes made.")

    except Exception as e:
        print(f"[FATAL ERROR] Failed to fix alias path in {BASHRC_PATH}. Error: {e}", file=sys.stderr)

def setup_api_key():
    print("Get your own Google Gemini API key from https://aistudio.google.com/app/api-keys")
    print("[INFO] This program won't check if your API key is correct.\nIf you provide an incorrect key, you have to edit it manually.")
    api_key = input("Paste your Gemini API Key here: ")

    api_key_line = f"export GEMINI_API_KEY={api_key}"

    new_block = f"""
# --- GEMINI API KEY (Auto-Generated by Linux Terminal Helper setup tool) ---
{api_key_line}
    """

    try:
        with open(BASHRC_PATH, 'a') as f:
            f.write(new_block)
        print(f"[SUCCESS] Gemini API Key installed in {BASHRC_PATH}.")
    except Exception as e:
        print(f"[FATAL ERROR] Failed to write the key to {BASHRC_PATH}. Check file permissions: {e}", file=sys.stderr)







def check_bashrc():

    alias_exists = False
    alias_is_correct = False
    api_key_exists = False

    expected_python_path = PATH / VENV_PYTHON_REL_PATH
    expected_script_path = PATH / MAIN_SCRIPT_REL_PATH

    expected_alias_path_part = f"{expected_python_path} {expected_script_path}"


    try:
        with open(BASHRC_PATH, 'r') as f:
            for line in f:
                line = line.strip()

                if line.startswith(ALIAS_PREFIX) and not line.startswith('#'):
                    alias_exists = True
                    if expected_alias_path_part in line:
                        alias_is_correct = True
                
                if line.startswith(API_KEY_PREFIX) and not line.startswith('#'):
                    api_key_exists = True

                if alias_exists and api_key_exists:
                    break
    except FileNotFoundError:
        print(f"Warning: {BASHRC_PATH} not found. The file will be created when you write to it.")
        return False
    
    except Exception as e:
        print(f"Error reading {BASHRC_PATH}: {e}", file=sys.stderr)
        return False
    
    return (alias_exists, alias_is_correct, api_key_exists)


def main():

    alias_found, alias_correct, key_found = check_bashrc()
    
    print("##Linux Terminal Helper Setup Tool##")
    print("========================================")
    print("checking for .bashrc entries...")
    print("Alias found:", alias_found)
    print("Alias path is correct:", alias_correct)
    print("API key found:", key_found)
    print("========================================")

    changes_made = False

    if not alias_found:
        print("alias entry 'helper' not found. Installing alias...")
        setup_alias()
        alias_correct = True
        changes_made = True
    elif not alias_correct:
        print("alias 'helper' found but pointing to wrong location. Updating path...")
        fix_alias_path()
        changes_made = True

    if not key_found:
        print("Gemini API Key not found. Starting install...")
        setup_api_key()
        changes_made = True

    if changes_made:
        print("[SUCCESS] Setup complete! You must run 'source ~/.bashrc' or open a new terminal to activate the changes.")
    elif key_found and alias_correct:
        print("[INFO] You're all setup!")




if __name__ == "__main__":
    main()